### ISSUE TITLE
simplest serverside rendering example possible, window undefined

### ISSUE THREAD

**Issue by ippa** [necolas/react-native-web#108]
```
$ cat test.js 
React = require('react-native-web')
React.renderToString('<div>test</div>')

$ node -v
v4.4.0

$ node test.js 
/tmp/node_modules/react-native-web/dist/apis/PanResponder/injectResponderEventPlugin.js:37
var supportsTouch = 'ontouchstart' in window || window.DocumentTouch && document instanceof window.DocumentTouch;
                                      ^

ReferenceError: window is not defined
    at Object.<anonymous> (/tmp/node_modules/react-native-web/dist/apis/PanResponder/injectResponderEventPlugin.js:37:39)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/node_modules/react-native-web/dist/index.js:25:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

libs installed as per readme instruction.

**Comment by necolas** [comment]
Thanks, this should be fixed in master.

FYI, your example is passing a string to `renderToString`.
