### ISSUE TITLE
react-native not getting resolved to react-native-web in server

### ISSUE THREAD

**Issue by priya-unacademy** [necolas/react-native-web#1125]
I used babel-plugin-react-native-web to resolve react-native to react-native-web on server side. Yet this doesn't seem to be helpful. It is still loading the node_modules/react-native.

* React Native for Web (version): 0.8.9
* React (version): 16.4.0
* Browser: Chrome
* Babel: 7
* Webpack: 4.18.6

`Error: Cannot find module 'NativeModules'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function._module2.default._resolveFilename (/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:442:34)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.get NativeModules [as NativeModules] (/node_modules/react-native/Libraries/react-native/react-native-implementation.js:111:32)
    at Object.<anonymous> (/node_modules/react-native-extra-dimensions-android/index.js:2:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
`

It is still trying to take from react-native and not from react-native-web. 

The code is running perfectly fine in client. What am I missing ?

**Comment by necolas** [comment]
Looks like you're importing react-native-extra-dimensions-android on web. Also make sure you are either processing your node module dependencies or bundling the server eg with webpack
