### ISSUE TITLE
Error: Cannot find module './modules/UnimplementedView' when StyleSheet.create is called

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#1220]
**The problem**
I updated Next.js to 8.0.0-canary.2 and when I run `StyleSheet.create`, this error is thrown:

```
{ Error: Cannot find module './modules/UnimplementedView'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object../modules/UnimplementedView (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:986:18)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:23:31)
    at Object../node_modules/react-native-web/dist/cjs/index.js (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:2941:26)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:23:31)
    at Module../themes/light.ts (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:3718:70)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:23:31)
    at Module../pages/_app.tsx (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:3500:72)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:3945:18)
    at __webpack_require__ (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:23:31)
    at /Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:91:18
    at Object.<anonymous> (/Users/steida/dev/este-typescript/.next/server/static/development/pages/_app.js:94:10) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './modules/UnimplementedView'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

With Next 7.0.2, everything works as expected.

**How to reproduce**
Not sure yet, because Next.js is server side framework.

Next.js obviously changed strategy (or bundled webpack), but I don't know if something was fixed or broken.
Maybe React Native Web does not export something correctly (because Next.js canary is ofter very stable), maybe not.

Feel free to close it, I created this issue so people can google it.

**Comment by necolas** [comment]
Yes it's likely a problem with Next.js

**Comment by heysailor** [comment]
For those googling - configuration for RNW with Next 8 is here: https://github.com/martpie/next-transpile-modules/issues/8#issuecomment-467679124

**Comment by steida** [comment]
Or here https://github.com/este/este
