### ISSUE TITLE
Remove all use of legacy context API

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1506]
**The problem**

The legacy context API is being used in a number of components. This API will eventually be deprecated and there are performance improvements to using the current context API.

**Comment by sergeymild** [comment]
I am still seeing that problem
```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: CellRenderer

Learn more about this warning here: https://reactjs.org/link/legacy-context
    at CellRenderer (http://localhost:3002/static/js/0.chunk.js:92083:36)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at http://localhost:3002/static/js/0.chunk.js:70871:34
    at ScrollView (http://localhost:3002/static/js/0.chunk.js:17993:37)
    at VirtualizedList (http://localhost:3002/static/js/0.chunk.js:90941:34)
    at FlatList (http://localhost:3002/static/js/0.chunk.js:88627:34)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at ProfileScreen (http://localhost:3002/static/js/0.chunk.js:24876:76)
    at StaticContainer (http://localhost:3002/static/js/0.chunk.js:2987:16)
    at EnsureSingleNavigator (http://localhost:3002/static/js/0.chunk.js:2697:3)
    at SceneView (http://localhost:3002/static/js/0.chunk.js:2884:3)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at CardSheet (http://localhost:3002/static/js/0.chunk.js:12009:3)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at AnimatedComponent (http://localhost:3002/static/js/0.chunk.js:85088:32)
    at AnimatedComponentWrapper
    at Dummy (http://localhost:3002/static/js/0.chunk.js:9907:3)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at AnimatedComponent (http://localhost:3002/static/js/0.chunk.js:85088:32)
    at AnimatedComponentWrapper
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at Card (http://localhost:3002/static/js/0.chunk.js:11251:5)
    at CardContainer (http://localhost:3002/static/js/0.chunk.js:11746:3)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at WebScreen (http://localhost:3002/static/js/0.chunk.js:11087:1)
    at AnimatedComponent (http://localhost:3002/static/js/0.chunk.js:85088:32)
    at AnimatedComponentWrapper
    at MaybeScreen (http://localhost:3002/static/js/0.chunk.js:11127:3)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at MaybeScreenContainer (http://localhost:3002/static/js/0.chunk.js:11109:3)
    at CardStack (http://localhost:3002/static/js/0.chunk.js:12211:5)
    at KeyboardManager (http://localhost:3002/static/js/0.chunk.js:10866:5)
    at SafeAreaProviderCompat (http://localhost:3002/static/js/0.chunk.js:11022:3)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at StackView (http://localhost:3002/static/js/0.chunk.js:12646:5)
    at StackNavigator (http://localhost:3002/static/js/0.chunk.js:9509:3)
    at EnsureSingleNavigator (http://localhost:3002/static/js/0.chunk.js:2697:3)
    at BaseNavigationContainer (http://localhost:3002/static/js/0.chunk.js:2373:3)
    at ThemeProvider (http://localhost:3002/static/js/0.chunk.js:6635:3)
    at NavigationContainer (http://localhost:3002/static/js/0.chunk.js:6345:3)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at NativeSafeAreaView (http://localhost:3002/static/js/0.chunk.js:66175:3)
    at SafeAreaProvider (http://localhost:3002/static/js/0.chunk.js:66354:3)
    at ThemeProvider (http://localhost:3002/static/js/0.chunk.js:607:31)
    at div
    at View (http://localhost:3002/static/js/0.chunk.js:76732:24)
    at App (http://localhost:3002/static/js/main.chunk.js:264:89)
```

**Comment by necolas** [comment]
The only legacy context use left is in the React Native vendor code, e.g., VirtualizedList, and needs to be fixed upstream
