### ISSUE TITLE
Cannot read property 'bindings' of null

### ISSUE THREAD

**Issue by arshidkv12** [necolas/react-native-web#1518]
Getting following error.

``ERROR in ./src/App.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/arshid/Desktop/test/myApp/src/App.js: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/arshid/Desktop/test/myApp/node_modules/@babel/traverse/lib/scope/index.js:822:13)
    at BlockScoping.updateScopeInfo (/Users/arshid/Desktop/test/myApp/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)``

**Comment by mayurmate149** [comment]
I Am also getting same Error

**Comment by necolas** [comment]
There isn't enough information in this issue. You should complete the template that is provided: https://raw.githubusercontent.com/necolas/react-native-web/master/.github/ISSUE_TEMPLATE/bug.md

This also looks like an issue with your local build process as RNW doesn't use babel in the public API
