### ISSUE TITLE
Compile babel-loader failed

### ISSUE THREAD

**Issue by toanhosss** [necolas/react-native-web#1524]
**The problem**
I have this error log when running compile, can you help me solve this issue. Thanks
`
> cargopedia@0.0.1 web /Users/xuantoan/Project/react-native/cargopedia-mobile
> webpack-dev-server -d --config ./web/webpack.config.js --inline --hot --colors

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/xuantoan/Project/react-native/cargopedia-mobile
✖ ｢wdm｣: Hash: e6157c0d032cc9862392
Version: webpack 4.41.5
Time: 1112ms
Built at: 01/21/2020 10:45:47 PM
        Asset     Size  Chunks             Chunk Names
bundle.web.js  4.5 MiB    main  [emitted]  main
Entrypoint main = bundle.web.js
[1] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.web.js 52 bytes {main} [built]
[./App.js] 1.64 KiB {main} [built] [failed] [1 error]
[./app.json] 57 bytes {main} [built]
[./index.web.js] 632 bytes {main} [built]
[./node_modules/@babel/runtime/helpers/interopRequireDefault.js] 147 bytes {main} [built]
[./node_modules/react-native-web/dist/exports/AppRegistry/index.js] 4.57 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
    + 141 hidden modules

ERROR in ./App.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/xuantoan/Project/react-native/cargopedia-mobile/App.js: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/@babel/traverse/lib/scope/index.js:822:13)
    at BlockScoping.updateScopeInfo (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/xuantoan/Project/react-native/cargopedia-mobile/node_modules/@babel/traverse/lib/context.js:84:19)
 @ ./index.web.js 1:340-356
 @ multi ./index.web.js
ℹ ｢wdm｣: Failed to compile.
`
**How to reproduce**

Simplified test case: 

Steps to reproduce:
1. In index.web.js:
https://prnt.sc/qquaoi
2. In App.js:
https://prnt.sc/qquc7a
3. run npm compile web : "./node_modules/.bin/webpack-dev-server -d --config ./web/webpack.config.js --inline --hot --colors"

**Expected behavior**
compile successfull

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.4
* React (version): 16.9.0
* Browser: Chrome for MacOS version 79.0.3945.130

**Comment by necolas** [comment]
No, I can't help with your webpack compiler issues. There are some notes in the docs. If that doesn't help you might have more luck on stackoverflow or webpack repo in setting up webpack.

**Comment by Bijiabo** [comment]
> No, I can't help with your webpack compiler issues. There are some notes in the docs. If that doesn't help you might have more luck on stackoverflow or webpack repo in setting up webpack.

The documentation was too rudimentary to be quickly integrated into existing projects, and I had the same problem. Maybe it can be improved later
@necolas
