### ISSUE TITLE
RequestAnimationFrame

### ISSUE THREAD

**Issue by elmpp** [necolas/react-native-web#1617]
I've searched through the issues and can't see anything specific to this and StackOverflow wasn't much help so here goes.

I'm seeing the following error during SSR. I can trace it through but am surprised to see explicit imports of `react-native` [via the vendor folders](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Animated/index.js#L10) whilst debugging. 

```
requestAnimationFrame is not defined
ReferenceError: requestAnimationFrame is not defined
```

As far as i can tell, the anchored [webpack alias](http://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page#web-packaging-for-existing-react-native-apps) would never catch that (as it doesn't). 

Should i expect to have problems re. requestAnimationFrame whilst SSR? [This SO question](https://stackoverflow.com/questions/61428508/requestanimationframe-is-not-defined-it-next-js-with-react-native-web-animated) mirrors my problem exactly.

Nextjs version: next@9.3.1
Expo next-adapter: @expo/next-adapter@2.0.5
RNW: react-native@0.61.2

Here is a dump of my webpack config - https://pastebin.com/7ZAHUSSr

**Comment by necolas** [comment]
What's the stack trace? And can you set up a test case on codesandbox?

**Comment by elmpp** [comment]
i'm having real trouble setting up a repro sorry, i've tried with smaller components but it's something about my work components that has some effect seemingly.

Stack trace:
```
ReferenceError: requestAnimationFrame is not defined
    at start (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/index.js:47830:11)
    at TimingAnimation.start (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/index.js:47838:7)
    at AnimatedValue.animate (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/index.js:49939:15)
    at start (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/index.js:46603:19)
    at Object.start (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/index.js:46609:7)
    at Object.start (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/index.js:46687:29)
    at fadeInAndOut (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/index.js:3416:909)
    at getAnimationStyle (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/index.js:3416:1740)
    at TemporaryView (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/index.js:3416:2873)
    at processChild (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
    at resolve (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/next/dist/next-server/server/render.js:83:16)
    at renderPage (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/next/dist/next-server/server/render.js:415:16)
    at Function._callee$ (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/_document.js:619:20)
    at tryCatch (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/mattpenrice/dev/nxg-rnw-repro/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/_document.js:206:24)
    at _next (/Users/mattpenrice/dev/nxg-rnw-repro/.next/server/static/development/pages/_document.js:228:9)
```


The crux of this problem is understanding why i'm seeing the following kind of modules in the bundle when they're imcompatible with SSR. Is this an indication i'm missing webpack or doing something wrong? (i can see they're imported from within [RNW](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Animated/index.js#L10)):

```
/***/ "./node_modules/react-native-web/dist/vendor/react-native/Animated/animations/DecayAnimation.js":
/*!******************************************************************************************************!*\
  !*** ./node_modules/react-native-web/dist/vendor/react-native/Animated/animations/DecayAnimation.js ***!
  \******************************************************************************************************/
/*! exports provided: default */
```

**Comment by elmpp** [comment]
Here's a better stacktrace.

Following this import:
`import { Animated } from 'react-native';`

```
Server Error
ReferenceError: requestAnimationFrame is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
start
node_modules/react-native-web/dist/vendor/react-native/Animated/animations/TimingAnimation.js (92:10)
TimingAnimation.start
node_modules/react-native-web/dist/vendor/react-native/Animated/animations/TimingAnimation.js (100:6)
AnimatedValue.animate
node_modules/react-native-web/dist/vendor/react-native/Animated/nodes/AnimatedValue.js (309:14)
start
node_modules/react-native-web/dist/vendor/react-native/Animated/AnimatedImplementation.js (141:18)
Object.start
node_modules/react-native-web/dist/vendor/react-native/Animated/AnimatedImplementation.js (147:6)
Object.start
node_modules/react-native-web/dist/vendor/react-native/Animated/AnimatedImplementation.js (225:28)
fadeInAndOut
node_modules/@24i/nextgen-sdk-gluons/src/components/TemporaryView/index.js (24:7)
getAnimationStyle
node_modules/@24i/nextgen-sdk-gluons/src/components/TemporaryView/index.js (52:8)
TemporaryView
node_modules/@24i/nextgen-sdk-gluons/src/components/TemporaryView/index.js (81:33)
processChild
file:///Users/mattpenrice/dev/nxg-rnw-repro/node_modules/react-dom/cjs/react-dom-server.node.development.js (3043:14)
resolve
file:///Users/mattpenrice/dev/nxg-rnw-repro/node_modules/react-dom/cjs/react-dom-server.node.development.js (2960:5)
ReactDOMServerRenderer.render
file:///Users/mattpenrice/dev/nxg-rnw-repro/node_modules/react-dom/cjs/react-dom-server.node.development.js (3435:22)
ReactDOMServerRenderer.read
file:///Users/mattpenrice/dev/nxg-rnw-repro/node_modules/react-dom/cjs/react-dom-server.node.development.js (3373:29)
```

**Comment by necolas** [comment]
You're calling a function in temporary view that is trying to run an animation on the server

**Comment by elmpp** [comment]
ah ok so i can't expect this (and other browser-specific) apis to be mocked out during SSR. (am kinda new to RNW and porting a library)

Thanks for the help
