### ISSUE TITLE
Issue with react-test-renderer's create function

### ISSUE THREAD

**Issue by shogunatealex** [necolas/react-native-web#1679]
**The problem**

Upon upgrading to .13.3 all of my jest tests have started failing. At one specific function, the create function from react-test-renderer. 

The simplified test will be a lot quicker to understand if you want to just skip to that. Basically can't use the create function of react-test-renderer. So I can't upgrade my project as I'm not going to introduce hundreds of failing tests.

Exact error is:
`TypeError: Cannot set property 'measure' of null`

Full stack is:

     TypeError: Cannot set property 'measure' of null

      83 |      } as any;
      84 | 
    > 85 |      const tree = createRender(<ParkDetails onAddStop={() => {}} />).toJSON();
         |                   ^
      86 |      expect(tree).toMatchSnapshot();
      87 | });
      88 | 

      at node_modules/react-native-web/dist/cjs/hooks/usePlatformMethods.js:63:22
      at imperativeHandleEffect (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6122:18)
      at commitHookEffectListMount (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10345:26)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10401:9)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13295:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9972:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10021:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10073:31)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13033:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1775:10)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12873:3)
      at finishSyncRender (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12384:3)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12370:7)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1825:24
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1775:10)
      at flushSyncCallbackQueueImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1820:7)
      at flushSyncCallbackQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1808:3)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11776:9)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14747:3)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15455:5)
      at src/app/park/Park/Park.spec.tsx:85:15

Console logging the hostRef from usePlatformMethods.js function usePlatformMethods results in 
` {current: null} `

**How to reproduce**
Simplified test case: https://codesandbox.io/s/epic-khorana-qook7

<img width="1415" alt="Screen Shot 2020-07-20 at 2 05 18 PM" src="https://user-images.githubusercontent.com/22369126/87970666-0e2baa00-ca92-11ea-8b7d-4514c4bc50b6.png">

Steps to reproduce:
1. Create a simple app. The sandbox above is great. Add the react-test-renderer
2. Create a simple test, try to use react-test-renderer's create function.
3. Should fail with a cannot set property 'measure' of null

**Expected behavior**

Expected that the test will complete successfully and without errors.

**Environment (include versions). Did this work in previous versions?**
Worked in 0.12.3, not in >=0.13.0

* React Native for Web (version): 0.13.3 (Works in 0.12.3, fails in >=0.13.0)
* React (version): 16.13.1
* Browser: N/A (Console error with jest)

**Comment by necolas** [comment]
Try 0.13.4

**Comment by shogunatealex** [comment]
0.13.4 works for fixing that bug. Thanks for getting that out so fast. Getting another error now. I will write up another issue for it @necolas .
