### ISSUE TITLE
Issue with react-test-renderer's create function (Part 2)

### ISSUE THREAD

**Issue by shogunatealex** [necolas/react-native-web#1680]
**The problem**
react-test-render isn't working for the Animated library from react-native. 

The simplified test will be a lot quicker to understand if you want to just skip to that.

Exact error is:
`TypeError: Cannot read property 'getScrollableNode' of null`

Full stack is:
   TypeError: Cannot read property 'getScrollableNode' of null

      4 | 
      5 | it('renders', () => {
    > 6 |       const tree = createRender(<Animated.View />).toJSON();
        |                    ^
      7 |       expect(tree).toMatchSnapshot();
      8 | });
      9 | 

      at AnimatedComponent._attachNativeEvents (node_modules/react-native-web/dist/cjs/vendor/react-native/Animated/createAnimatedComponent.js:113:44)
      at AnimatedComponent.componentDidMount (node_modules/react-native-web/dist/cjs/vendor/react-native/Animated/createAnimatedComponent.js:105:12)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9432:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10829:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2377:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2427:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2480:31)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11041:7)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12492:5
      at Object.unstable_runWithPriority (node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12491:13)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12420:9)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12328:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12302:3)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12171:5)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11986:5)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12585:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12613:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12624:10)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13057:5)
      at Object.<anonymous> (src/widgets/Progress/Progress.spec.tsx:6:15)

**How to reproduce**

Simplified test case: https://codesandbox.io/s/sleepy-wildflower-4zm7g?file=/src/App.test.js

<img width="1415" alt="Screen Shot 2020-07-20 at 3 44 17 PM" src="https://user-images.githubusercontent.com/22369126/87979320-e17e8f00-ca9f-11ea-91a5-0fe8e33ee2c4.png">

Steps to reproduce:
1. Fork the codesandbox.io
2. Add react-test-renderer to the list of dependencies
3. Try to render a <Animated.View> with the create function

**Expected behavior**

The test should pass, it currently fails with an error.

**Environment (include versions). Did this work in previous versions?**

Works on 0.12.4 but fails on anything >=0.13.0

* React Native for Web (version): 0.13.4 
* React (version): 16.13.1
* Browser: N/A (Console error with Jest)

**Comment by necolas** [comment]
Hmm. Off the top of my head, I dont know why the ref would be `null` in 0.13. I thought `react-test-renderer` might not support refs but then 0.12 should have been failing too

**Comment by cbstauss** [comment]
React Native's createAnimatedComponent doesn't support stateless functional components. Is that the issue here?

https://github.com/facebook/react-native/blob/973198667d7bbbf3b5d8890fc0a53dc99d0bce18/Libraries/Animated/src/createAnimatedComponent.js#L45

**Comment by shogunatealex** [comment]
Yeah I think it's related to this stackoverflow question:
https://stackoverflow.com/questions/41425178/using-animated-with-styled-components-react-native/41486399#41486399

Unfortunately, this has been an issue for 3 years @necolas and it doesn't look like React native is going to fix it anytime soon. Should we open a PR to revert the animated components back to class based?
