### ISSUE TITLE
AnimatedValue.interpolate fails invariant on 0.16.0

### ISSUE THREAD

**Issue by linco95** [necolas/react-native-web#2001]
**The problem**

Trying to render Paper UI Card component with dark theme and adaptive mode will fail invariant in AnimatedInterpolation. 

**How to reproduce**

~~I was not able to recreate this in codesandbox as Paper UI failed to load for some reason.~~ EDIT: I still couldn't get paper to work in code sandbox, but I extracted the logic and reproduced the bug. Changing to 0.15.7 in the codesandbox and it doesn't crash.
Simplified test case: https://codesandbox.io/s/jolly-jennings-ydfc5?file=/src/App.js

I was however able to inspect the sources of my application and this should probably be enough to create a unit test for interpolate function:
`const conf = {
    "inputRange": [
        0,
        1,
        2,
        3,
        8,
        24
    ],
    "outputRange": [
        "#1E1E1E",
        "#1E1E1E",
        "#232323",
        "#252525",
        "#2E2E2E",
        "#383838"
    ]
};
const animVal = new AnimatedValue(1);
animVal.interpolate(conf);`

If I have more time I might be able to create a reduced expo app and add it here.
Steps to reproduce:
1. Create a new expo app
2. Add react-paper-ui
3. Ensure dark theme and adaptive mode
4. Try to render paper UI card component

Looking at the stack trace it seems like it is the Surface component that's actually crashing.

> Invariant Violation: invalid pattern #1E1E1E and #232323
    at invariant (http://localhost:19006/static/js/bundle.js:117326:15)
    at checkPattern (http://localhost:19006/static/js/bundle.js:110755:62)
    at createInterpolationFromStringOutputRange (http://localhost:19006/static/js/bundle.js:110718:3)
    at createInterpolation (http://localhost:19006/static/js/bundle.js:110612:12)
    at new AnimatedInterpolation (http://localhost:19006/static/js/bundle.js:110793:28)
    at AnimatedValue.interpolate (http://localhost:19006/static/js/bundle.js:112235:12)
    at overlay (http://localhost:19006/static/js/bundle.js:92331:22)
    at Surface (http://localhost:19006/static/js/bundle.js:88063:124)
    at renderWithHooks (http://localhost:19006/static/js/bundle.js:60528:18)
    at mountIndeterminateComponent (http://localhost:19006/static/js/bundle.js:63354:13)
    at beginWork (http://localhost:19006/static/js/bundle.js:64592:16)
    at HTMLUnknownElement.callCallback (http://localhost:19006/static/js/bundle.js:49488:14)
    at Object.invokeGuardedCallbackDev (http://localhost:19006/static/js/bundle.js:49537:16)
    at invokeGuardedCallback (http://localhost:19006/static/js/bundle.js:49599:31)
    at beginWork$1 (http://localhost:19006/static/js/bundle.js:69502:7)
    at performUnitOfWork (http://localhost:19006/static/js/bundle.js:68314:12)
    at workLoopSync (http://localhost:19006/static/js/bundle.js:68245:5)
    at renderRootSync (http://localhost:19006/static/js/bundle.js:68208:7)
    at performSyncWorkOnRoot (http://localhost:19006/static/js/bundle.js:67831:18)
    at http://localhost:19006/static/js/bundle.js:56870:26
    at unstable_runWithPriority (http://localhost:19006/static/js/bundle.js:72684:12)
    at runWithPriority$1 (http://localhost:19006/static/js/bundle.js:56819:10)
    at flushSyncCallbackQueueImpl (http://localhost:19006/static/js/bundle.js:56865:9)
    at flushSyncCallbackQueue (http://localhost:19006/static/js/bundle.js:56852:3)
    at flushPassiveEffectsImpl (http://localhost:19006/static/js/bundle.js:69158:3)
    at unstable_runWithPriority (http://localhost:19006/static/js/bundle.js:72684:12)
    at runWithPriority$1 (http://localhost:19006/static/js/bundle.js:56819:10)
    at flushPassiveEffects (http://localhost:19006/static/js/bundle.js:68985:14)
    at http://localhost:19006/static/js/bundle.js:68862:11
    at workLoop (http://localhost:19006/static/js/bundle.js:72633:34)
    at flushWork (http://localhost:19006/static/js/bundle.js:72606:14)
    at MessagePort.performWorkUntilDeadline (http://localhost:19006/static/js/bundle.js:72373:27)

**Expected behavior**

No crash on iOS. Expect this not to crash simply. 
**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.16.1
* React (version): 17.0.2
* Browser: Chrome
* expo: 41.0.1
* React Native Paper: 4.8.0

No crash in 0.15.7

**Comment by linco95** [comment]
Added codepen example

**Comment by jamesisaac** [comment]
Can confirm same issue.  Most color combination I've tried, such as the following:

```
const backgroundColor = valueAnim.interpolate({
  inputRange: [0, 1],
  outputRange: ['#000000', '#ffffff'],
});
```

work on RNWeb 0.15.7, but crash on 0.16.0, with message the message mentioned in original report about `invalid pattern #000000 and #ffffff`.

Strangely, some color combinations, e.g. `['#ff0000', '#00ff00']` manage to bypass (?) this invariant warning, and give a different error:

```
Uncaught TypeError: outputRanges[i] is undefined
    createInterpolationFromStringOutputRange AnimatedInterpolation.js:182
    createInterpolationFromStringOutputRange AnimatedInterpolation.js:181
    createInterpolationFromStringOutputRange AnimatedInterpolation.js:177
    createInterpolation AnimatedInterpolation.js:43
    AnimatedInterpolation AnimatedInterpolation.js:274
    interpolate AnimatedValue.js:222
    ...
```
