### ISSUE TITLE
Dependency issues when running npx command

### ISSUE THREAD

**Issue by saricden** [necolas/react-native-web#2362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When running `npx create-react-native-dapp` and after filling out the app details (name, etc.) the process begins to install dependencies. However, this fails with the following error:

```
✔ What is your app named? … Test
✔ What is the URI scheme? … test
✔ Downloaded and extracted project files.

Using npm to install packages.

✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following npm commands.

- cd Test
- npm run android
- npm run ios # you need to use macOS to build the iOS project - use the Expo app if you need to do iOS development without a Mac
- npm run web
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@1.0.0
npm ERR! Found: react-native@0.68.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.68.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.60.6 || ^0.61.5 || ^0.62.2 || ^0.63.2 || ^0.64.0 || 1000.0.0" from @react-native-async-storage/async-storage@1.13.4
npm ERR! node_modules/@react-native-async-storage/async-storage
npm ERR!   @react-native-async-storage/async-storage@"1.13.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/kirk/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kirk/.npm/_logs/2022-08-10T11_47_59_466Z-debug-0.log
node:internal/errors:841
  const err = new Error(message);
              ^

Error: Command failed: npm i
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at shouldInstall (/home/kirk/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/buidler/index.js:534:48)
    at Object.create (/home/kirk/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/buidler/index.js:777:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/kirk/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/cli/index.js:119:33 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 88696,
  stdout: null,
  stderr: null
}
```

### Expected behavior

A new react-native dapp should be bootstrapped.

### Steps to reproduce

1. Run the command
2. Fill out the requested info
3. That's it

### Test case

https://notneccesarry.nope

### Additional comments

This tool looks fantastic, and in the meantime I'm going to bootstrap my project via a previous working version.
Thank you for all your hard work!

**Comment by saricden** [comment]
Omg wrong repo. So sorry.
