### ISSUE TITLE
Vite in a SSR context

### ISSUE THREAD

**Issue by zoriya** [necolas/react-native-web#2668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When using react-native-web with vite in SSR, it simply does not work. There seems to be due to issues with commonjs/modules handling.

After adding "inline-style-prefixer" to the list of commonJS packages to fix, rnw fails to load due to a module error on `vendor/react-native/Utilities/clamp.js` 

### Expected behavior

SSR should work on vite

### Steps to reproduce

- Create a new vite with ssr project
- install `vite-plugin-react-native-web` to replace `react-native` imports with `react-native-web`
- install `vite-plugin-cjs-interop` and add `inline-style-prefixer` to the list of packages to interop
- Start the project and acess a page

### Test case

https://github.com/zoriya/vite-rnw-ssr-repro

### Additional comments

With @brillout, the creator of Vike (a SSR framework for vite), we tried to debug this the best we can, you can find our discussion and the vite issue below:

https://github.com/vikejs/vike/discussions/1637
https://github.com/vitejs/vite/issues/16679

**Comment by zoriya** [comment]
Turns out, import errors can be fixed by adding `react-native-web` to the list `ssr.optimizeDeps.include` like so:

```typescript
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import reactNative from "vite-plugin-react-native-web";
import { cjsInterop } from "vite-plugin-cjs-interop";

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [
		react(),
		reactNative(),
		cjsInterop({
			dependencies: ["inline-style-prefixer", "inline-style-prefixer/**"],
		}),
	],
	ssr: {
		optimizeDeps: {
			include: ["react-native-web"],
		},
	},
});

```

Now the error is really wild while using a react-native-web componant in SSR:

```shell
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext6 (/home/zoriya/projects/rnw-ssr-vite/node_modules/.vite/deps_ssr/react-native-web.js?v=7a5478b2:3119:29)
    at /home/zoriya/projects/rnw-ssr-vite/node_modules/.vite/deps_ssr/react-native-web.js?v=7a5478b2:29254:32
    at renderWithHooks (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5662:16)
    at renderForwardRef (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5846:18)
    at renderElement (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6009:11)
    at renderNodeDestructiveImpl (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderNode (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6263:12)
    at renderChildrenArray (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6215:7)
    at renderNodeDestructiveImpl (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6145:7)
    at renderNodeDestructive (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderElement (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5975:9)
    at renderNodeDestructiveImpl (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderIndeterminateComponent (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5789:7)
    at renderElement (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderElement (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5975:9)
    at renderNodeDestructiveImpl (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at retryTask (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6532:5)
    at performWork (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6580:7)
    at /home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6904:12
    at scheduleWork (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:78:3)
    at startWork (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6903:3)
    at renderToStringImpl (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6977:3)
    at Object.renderToString (/home/zoriya/projects/rnw-ssr-vite/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:7065:10)
    at render (/home/zoriya/projects/rnw-ssr-vite/src/entry-server.jsx:6:31)
    at file:///home/zoriya/projects/rnw-ssr-vite/server.js:54:28

```

**Comment by brillout** [comment]
Vike author here, this affects all Vite-based SSR frameworks. Not only Vike but also Remix, etc. Thus RNW cannot be used in all these frameworks.

**Comment by zoriya** [comment]
So I fixed that and the issue with hooks went away, I was not expecting that. I guess it's because using `ssr.optimizeDeps.include` also included dependencies like react.

I also looked at `inline-style-prefixer`, that you include via it's cjs entrypoint (`/lib`). I could not make it run via it's ejs entrypoint, which I think is due to an upstream bug. I'll try to fix this too soon.

**Comment by jkhaui** [comment]
@zoriya have you tried using npm aliases to install react-native-web instead of using the Vite plugin? This is how I normally set it up with Vite SSR-based frameworks and it seems to work.

Like so in your package.json:

`"react-native": "npm:react-native-web"`

**Comment by zoriya** [comment]
This prevents using react-native on platforms other than web.

For anyone else finding this issue:
I stopped trying to make rnw run w/ vite & ssr. Most react native packages are cjs only (expo for example almost never ships esm). This leads to too many issues for me to consider vite a viable bundler for react-native. I am hopping we get a solution soon either via a new ssr framework based on bun, via react-native switching to esm or via vite working better w/ cjs.

**Comment by jkhaui** [comment]
> This prevents using react-native on platforms other than web.

 I can't help you much more because I only use rn on web (building an SSR framework with react-navigation as a universal router). 

But if it's at least working on web now, could you do something like dynamically change the package source to use "actual" rn (instead of aliased rnw) depending on your environment?

I'm not sure how exactly, but dynamic imports + environment variables could be enough to achieve this. Or you could have a local copy of rnw symlinked, etc. Huge PITA for sure though
 
> This leads to too many issues for me to consider vite a viable bundler for react-native. I am hopping we get a solution soon either via a new ssr framework based on bun, via react-native switching to esm or via vite working better w/ cjs.

I feel you. I tried to push some major rn packages to be more esm-friendly but got too busy to continue.
Try checking out [Nate's vxrn repo](https://github.com/universal-future/vxrn) before throwing in the towel. We need more people working on Vite and cross-platform solutions.

**Comment by Bram-dc** [comment]
I created `vite-plugin-react-native-web` and never had this issue untill now. I have recreated the plugin to work with Vite 8. I am getting this issue now during dev (not even using ssr). And I am unable to fix this issue. I am wondering what changed in vite that I now get this issue.

**Comment by esiconplc** [comment]
instead of "vite-plugin-cjs-interop"
just add 
```
optimizeDeps: {
  include: [
    "inline-style-prefixer/lib/createPrefixer",
    "inline-style-prefixer/lib/plugins/backgroundClip",
    "inline-style-prefixer/lib/plugins/crossFade",
    "inline-style-prefixer/lib/plugins/cursor",
    "inline-style-prefixer/lib/plugins/filter",
    "inline-style-prefixer/lib/plugins/imageSet",
    "inline-style-prefixer/lib/plugins/logical",
    "inline-style-prefixer/lib/plugins/position",
    "inline-style-prefixer/lib/plugins/sizing",
    "inline-style-prefixer/lib/plugins/transition"
  ]
}
```
works for me

with pnpm also add peerDep "inline-style-prefixer": "*"

**Comment by Bram-dc** [comment]
> instead of "vite-plugin-cjs-interop" just add
> 
> ```
> optimizeDeps: {
>   include: [
>     "inline-style-prefixer/lib/createPrefixer",
>     "inline-style-prefixer/lib/plugins/backgroundClip",
>     "inline-style-prefixer/lib/plugins/crossFade",
>     "inline-style-prefixer/lib/plugins/cursor",
>     "inline-style-prefixer/lib/plugins/filter",
>     "inline-style-prefixer/lib/plugins/imageSet",
>     "inline-style-prefixer/lib/plugins/logical",
>     "inline-style-prefixer/lib/plugins/position",
>     "inline-style-prefixer/lib/plugins/sizing",
>     "inline-style-prefixer/lib/plugins/transition"
>   ]
> }
> ```
> 
> works for me
> 
> with pnpm also add peerDep "inline-style-prefixer": "*"

Thanks! This was the missing piece to get the plugin working.

https://github.com/Bram-dc/vite-plugin-react-native-web/commit/18be534e37159d00f1547282dc2235d47779c380

**Comment by esiconplc** [comment]
> > instead of "vite-plugin-cjs-interop" just add
> > ```
> > optimizeDeps: {
> >   include: [
> >     "inline-style-prefixer/lib/createPrefixer",
> >     "inline-style-prefixer/lib/plugins/backgroundClip",
> >     "inline-style-prefixer/lib/plugins/crossFade",
> >     "inline-style-prefixer/lib/plugins/cursor",
> >     "inline-style-prefixer/lib/plugins/filter",
> >     "inline-style-prefixer/lib/plugins/imageSet",
> >     "inline-style-prefixer/lib/plugins/logical",
> >     "inline-style-prefixer/lib/plugins/position",
> >     "inline-style-prefixer/lib/plugins/sizing",
> >     "inline-style-prefixer/lib/plugins/transition"
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > works for me
> > with pnpm also add peerDep "inline-style-prefixer": "*"
> 
> Thanks! This was the missing piece to get the plugin working.
> 
> [Bram-dc/vite-plugin-react-native-web@18be534](https://github.com/Bram-dc/vite-plugin-react-native-web/commit/18be534e37159d00f1547282dc2235d47779c380)

but this works only for dev, build still broken

**Comment by Bram-dc** [comment]
Yeah I havent gotten to SSR yet, working on it now. Atleast my example apps are working in dev and build. Also all my other production apps work now.

**Comment by esiconplc** [comment]
so at the end I come with this, works for both dev and build 
```
resolve: { 
  alias: {
    /* vite8 + react-native-web build issues */
    "inline-style-prefixer/lib": "inline-style-prefixer/es",
    "css-in-js-utils/lib": "css-in-js-utils/es"
  }
}
```

**Comment by esiconplc** [comment]
Issue in fixed. tested on vite 8.0.3
