### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by gethinwebster** [necolas/react-native-web#293]
Adding as a placeholder, pending further investigation - full details to follow. Seems to have started happening somewhere between 0.0.56 and 0.0.60, happens when entering text in a TextInput.

```
ReactNative.js:3 Uncaught TypeError: Cannot read property 'x' of undefined
    at t.<anonymous> (https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:3:9021)
    at https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:3:8495
    at u (https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:1:20045)
    at Object.measure (https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:1:20172)
    at t.measure (https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:3:8077)
    at t.e._handleLayout (https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:3:8991)
    at t.e.componentDidUpdate (https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:3:8876)
    at r.notifyAll (https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:18:335)
    at r.close (https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:23:18428)
    at r.closeAll (https://unpkg.com/react-native-web@0.0.60/dist/ReactNative.js:2:7943)
```

**What is the current behavior?**

Link to minimal test case: (template: [codepen](https://codepen.io/necolas/pen/PZzwBR?editors=0010))

**What is the expected behaviour?**

**Steps to reproduce**

1.
2.

**Environment (include versions)**

OS:
Device:
Browser:
React Native for Web (version):
React (version):

**Comment by necolas** [comment]
I think there are some issues with the UMD build for `Image` too. It's only there for codepen use really.

**Comment by gethinwebster** [comment]
Caused by an error elsewhere in a lifecycle method, closing.
