### ISSUE TITLE
react-native-web

### ISSUE THREAD

**Issue by xiaoqianggeaaa** [necolas/react-native-web#840]
ERROR in ./index.web.js
Module build failed: F:\cailv\cailv-mobile\node_modules\react-navigation\src\createNavigationContainer.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.get createNavigationContainer [as createNavigationContainer] (F:\cailv\cailv-mobile\node_modules\react-navigation\src\react-navigation.js:6:12)

**Comment by walleXD** [comment]
@xiaoqianggeaaa You need to give all of us more context about what you are trying to do and where you face the issue? Error message without context is just not helpful

**Comment by necolas** [comment]
React navigation doesn't support web. But it looks like the package is not compiled and the node module needs to be compiled as described in the docs
