### ISSUE TITLE
errors in build

### ISSUE THREAD

**Issue by optimatex** [necolas/react-native-web#851]
**Do you want to request a *feature* or report a *bug*?**
report a bug
**What is the current behavior?**
```
ERROR in ./web/main.js
Module build failed: ReferenceError: document is not defined
    at hasCanvas (S:\front\node_modules\art\modes\fast-noSideEffects.js:3:16)
    at Object.<anonymous> (S:\front\node_modules\art\modes\fast-noSideEffects.js:8:5)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at S:\front\node_modules\react-art\cjs\react-art.development.js:27:25
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server web/main.js
```
**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. Install react-native-web
2. Add `"react-native-web"` as a plugin  and "react-native" as presets in `.babelrc `
3. Launch webpack 

**Environment (include versions). Did this work in previous versions?**

* OS: Windows
* React Native for Web (version): 0.4.0
* React (version): 16.2.0

**Comment by optimatex** [comment]
I have searched in other threads but those solutions did nit help me
My current .babelrc is next 
```
{
  "presets": [
    "react",
    "react-native",
    "es2015",
    "stage-1"
  ],
  "plugins": [
    "react-native-web",
    "transform-decorators-legacy"
  ]
}

```

and my webpack config is next 
```
context: path.resolve(__dirname, '../'),
  entry: {
    // server_bundle: './web/server_index.js',
    main: 'web/main.js',
  },
  output: {
    filename: '[name].js',
    path: path.join(__dirname, 'dist'),
    publicPath: '/static/',
  },
  devtool: 'cheap-module-eval-source-map',
  plugins: [
    new ExtractTextPlugin('dark.css', { allChunks: true }),
    new webpack.DefinePlugin({ 'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'dev') }),
    new webpack.HotModuleReplacementPlugin(),
  ],
  module: {
    loaders: [
      {
        test: /\.js(x?)$/,
        exclude: /node_modules/,
        loader: ['babel-loader'],
      }
    ]
  },
  resolve: {
    extensions: ['.tsx', '.js', '.jsx'],
    modules: [
      path.resolve(__dirname, '../src'),
      'node_modules',
    ],
  },
  watch: true,
  watchOptions: {
    aggregateTimeout: 100,
  },
```

**Comment by necolas** [comment]
Delicate of https://github.com/necolas/react-native-web/issues/737
