### ISSUE TITLE
Next.js example does not work with RNW 0.6.0

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#899]
I took this example https://github.com/zeit/next.js/tree/canary/examples/with-react-native-web and updated react-native-web and babel-plugin-react-native-web to 0.6.0 version.

I am not sure what I am doing wrong. Thank you for any hint. 

```
TypeError: Cannot read property 'initialProps' of undefined
    at Object.getApplication (/Users/steida/dev/with-react-native-web-app/node_modules/react-native-web/dist/exports/AppRegistry/index.js:59:126)
    at Function.getApplication (/Users/steida/dev/with-react-native-web-app/node_modules/react-native-web/dist/exports/AppRegistry/index.js:53:30)
    at Function.getApplication (/Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/webpack:/pages/_document.js?2bd2:20:45)
    at tryCatch (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/_document.js:96:191)
    at /Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/_document.js:96:437
    at new Promise (<anonymous>)
    at Function.<anonymous> (/Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/_document.js:96:99)
    at Function.getInitialProps (/Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/_document.js:212:22)
    at _callee$ (/Users/steida/dev/with-react-native-web-app/node_modules/next/dist/lib/utils.js:36:30)
    at tryCatch (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/steida/dev/with-react-native-web-app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
TypeError: Cannot read property 'initialProps' of undefined
    at Object.getApplication (/Users/steida/dev/with-react-native-web-app/node_modules/react-native-web/dist/exports/AppRegistry/index.js:59:126)
    at Function.getApplication (/Users/steida/dev/with-react-native-web-app/node_modules/react-native-web/dist/exports/AppRegistry/index.js:53:30)
    at Function.getApplication (/Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/webpack:/pages/_document.js?2bd2:20:45)
    at tryCatch (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/_document.js:96:191)
    at /Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/_document.js:96:437
    at new Promise (<anonymous>)
    at Function.<anonymous> (/Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/_document.js:96:99)
    at Function.getInitialProps (/Users/steida/dev/with-react-native-web-app/.next/dist/bundles/pages/_document.js:212:22)
    at _callee$ (/Users/steida/dev/with-react-native-web-app/node_modules/next/dist/lib/utils.js:36:30)
    at tryCatch (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/steida/dev/with-react-native-web-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/steida/dev/with-react-native-web-app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
TypeError: Cannot read property 'initialProps' of undefined
```

**Comment by necolas** [comment]
Pass config object as second argument to getApplication

**Comment by steida** [comment]
It helps, thank you.

**Comment by necolas** [comment]
I'll push a patch fix because it shouldn't blow up without the initial config. Thanks

**Comment by steida** [comment]
Also, for some reason, Next.js styled JSX within RNW breaks server-side rendering. I believe for some web edge cases it should be possible to use styled jsx. Maybe _document integration...

```js
export default props => (
  <View style={styles.container}>
    <Text style={styles.text}>Welcome to Next.js!</Text>
    <div>
      <h1>h1</h1>
      <style jsx>{`
        h1 {
          color: red;
        }
      `}</style>
    </div>
  </View>
);
```

**Comment by steida** [comment]
I believe this is the right approach for Next.js example.

```js
// @flow
import * as React from 'react';
import Document, { Head, Main, NextScript } from 'next/document';
import { AppRegistry } from 'react-native-web';

// https://github.com/zeit/next.js/tree/master/examples/with-react-native-web
// https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md#server-side-rendering
// https://github.com/zeit/next.js/tree/master/examples/with-react-intl

// Force Next-generated DOM elements to fill their parent's height.
// Not required for using of react-native-web, but helps normalize
// layout for top-level wrapping elements.
// Disable input, textarea outline because blinking caret is enough.
const normalizeNextElements = `
  body > div:first-child,
  #__next {
    height: 100%;
  }
  input, textarea {
    outline: none;
  }
`;

export default class MyDocument extends Document {
  static async getInitialProps(context: Object) {
    AppRegistry.registerComponent('Main', () => Main);
    const { getStyleElement } = AppRegistry.getApplication('Main', {});
    const props = await super.getInitialProps(context);
    const styles = React.Children.toArray([
      props.styles,
      <style dangerouslySetInnerHTML={{ __html: normalizeNextElements }} />,
      getStyleElement(),
    ]);

    return {
      ...props,
      locale: context.req.locale,
      localeDataScript: context.req.localeDataScript,
      // supportedLocales: context.req.supportedLocales,
      styles,
    };
  }

  render() {
    const { locale, localeDataScript /*, supportedLocales */ } = this.props;

    return (
      <html lang={locale} style={{ height: '100%', width: '100%' }}>
        <Head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {/* {supportedLocales.map(() => {
            // TODO: https://github.com/este/este/issues/1399
            return (
              <link
            href={`https://${locale}.${'deployDomainHere'}`}
            hrefLang={locale}
            key={locale}
            rel="alternate"
              />
            );
          })} */}
        </Head>
        <body style={{ height: '100%', width: '100%', overflowY: 'scroll' }}>
          <Main />
          <script dangerouslySetInnerHTML={{ __html: localeDataScript }} />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

**Comment by necolas** [comment]
I don't really understand the Next.js API and it doesn't seem to be well documented. Reading through their source code I wasn't sure how to render the returned element from `AppRegistry`, which means you can't use `AppRegistry` to get the application's root element on the server or the client.

Apart from that issue, it could be something like this:

```js
// i18n.js

const rtlLocales = [
  'ae', // Avestan
  'ar', // Arabic
  'arc', // Aramaic
  'bcc', // Southern Balochi
  'bqi', // Bakthiari
  'ckb', // Sorani
  'dv', // Dhivehi
  'fa', 'far', // Persian
  'glk', // Gilaki
  'he', 'iw', // Hebrew
  'khw', // Khowar
  'ks', // Kashmiri
  'ku', // Kurdish
  'mzn', // Mazanderani
  'nqo',  // N'Ko
  'pnb', // Western Punjabi
  'ps', // Pashto
  'sd', // Sindhi
  'ug', // Uyghur
  'ur', // Urdu
  'yi' // Yiddish
];

export const isLocaleRTL = locale => rtlLocales.indexOf(locale) >= 0;
```

```js
import Document, { Head, Main, NextScript } from 'next/document'
import React from 'react'
import { AppRegistry, I18nManager } from 'react-native-web'
import { isLocaleRTL } from './i18n'

// Force Next-generated DOM elements to fill their parent's height.
// Not required when using react-native-web, but helps normalize
// layout for top-level wrapping elements.
const normalizeNextElements = `
  body > div:first-child,
  #__next {
    height: 100%;
  }
`

AppRegistry.registerComponent('Main', () => Main)

export default class MyDocument extends Document {
  static async getInitialProps (context) {
    const locale = context.req.locale;

    // Use RTL layout for appropriate locales. Remember to do this client-side too.
    I18nManager.setPreferredLanguageRTL(isLocaleRTL(locale));

    // Get the html and styles needed to render this page.
    const { getStyleElement } = AppRegistry.getApplication('Main')
    const page = context.renderPage();
    const styles = React.Children.toArray([
      <style dangerouslySetInnerHTML={{ __html: normalizeNextElements }} />,
      props.styles,
      getStyleElement(),
    ]);

    return { ...page, locale, styles }
  }

  render () {
    const { locale } = this.props;

    return (
      <html lang={locale} style={{ height: '100%', width: '100%' }}>
        <Head>
          <title>react-native-web</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        // replace 'overflowY:scroll' with 'overflow:hidden' if relying on ScrollView
        <body style={{ height: '100%', width: '100%', overflowY: 'scroll' }}>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

**Comment by steida** [comment]
Thank you. JFYI, that's what I am using in Este https://github.com/este/este/blob/master/pages/_document.js
