### ISSUE TITLE
Not rendering on Chrome 41 / Google bot

### ISSUE THREAD

**Issue by pyankoff** [necolas/react-native-web#945]
I'm using RNW with Next.js as in this example https://github.com/zeit/next.js/tree/canary/examples/with-react-native-web

Pages load in newer browsers, but fail to load in Googlebot / Chrome 41. Here is an error:

```
undefined is not a function
TypeError: undefined is not a function
    at Object.webpackJsonp../node_modules/react-native-web/dist/exports/Image/ImageStylePropTypes.js (node_modules/react-native-web/dist/exports/Image/ImageStylePropTypes.js:41:0)
    at __webpack_require__ (webpack:/webpack/bootstrap b028a92304fecd251efd:714:0)
    at fn (webpack:/webpack/bootstrap b028a92304fecd251efd:117:0)
    at Object.webpackJsonp../node_modules/react-native-web/dist/exports/StyleSheet/StyleSheetValidation.js (node_modules/react-native-web/dist/exports/StyleSheet/StyleSheetValidation.js:5:0)
    at __webpack_require__ (webpack:/webpack/bootstrap b028a92304fecd251efd:714:0)
    at fn (webpack:/webpack/bootstrap b028a92304fecd251efd:117:0)
    at http://localhost:3000/_next/-/page/index.js:3603:36
    at Array.forEach (native)
    at Object.create (node_modules/react-native-web/dist/exports/StyleSheet/StyleSheet.js:49:0)
    at Object.webpackJsonp../node_modules/react-native-web/dist/modules/createDOMProps/index.js (node_modules/react-native-web/dist/modules/createDOMProps/index.js:30:0)index.js:368 _callee3$runtime.js:62 tryCatchruntime.js:296 invokeruntime.js:114 module.exports.webpackJsonp../node_modules/regenerator-runtime/runtime.js.forEach.prototype.(anonymous function)asyncToGenerator.js:12 stepasyncToGenerator.js:27 _nextes6.promise.js:75 module.exports.webpackJsonp../node_modules/core-js/library/modules/es6.promise.js.runes6.promise.js:92 (anonymous function)_microtask.js:18 module.exports.webpackJsonp../node_modules/core-js/library/modules/_microtask.js.module.exports.flush
```

Any idea how to fix?

**Comment by pyankoff** [comment]
Fixed it by using this plugin: https://github.com/sheerun/targets-webpack-plugin 
Closing, not deleting just in case someone has the same problem.

**Comment by necolas** [comment]
What's the problem that plugin is fixing?

**Comment by pyankoff** [comment]
As far as I understood it transforms the code removing the features available only in newer browsers. Like arrow functions.

**Comment by necolas** [comment]
The package is compiled before it is published, i.e., there are no arrow functions.

**Comment by pyankoff** [comment]
Hm, I'm not sure then 😕Picked this explanation up from one of the comments on a similar issue https://github.com/zeit/next.js/issues/3126#issuecomment-338393070 
Haven't looked into it myself, just slapped the plugin and moved on 😆
